In [ ]:
import pandas as pd
import numpy as np
data = {
    'x1': [1, 2, 3, 7, 8, 9],
    'x2': [2, 3, 4, 6, 7, 8],
    'x3': [5, 4, 3, 3, 2, 1],
    'y': [0, 0, 0, 1, 1, 1]
}
df = pd.DataFrame(data)
display(df)

   x1  x2  x3  y
0   1   2   5  0
1   2   3   4  0
2   3   4   3  0
3   7   6   3  1
4   8   7   2  1
5   9   8   1  1

In [ ]:
correlations = df.corr()['y'].drop('y')
print("Pearson Correlation with target 'y':",correlations)

Pearson Correlation with target 'y': x1    0.964901
x2    0.925820
x3   -0.774597
Name: y, dtype: float64

In [ ]:
from itertools import combinations
def cfs_merit(subset, df, target_col):
    if not subset:
        return 0.0
    k = len(subset)
    r_cf_sum = 0
    for feature in subset:
        r_cf_sum += df[feature].corr(df[target_col])
    avg_r_cf = r_cf_sum / k
    r_ff_sum = 0
    num_feature_pairs = 0
    if k > 1:
        for f1, f2 in combinations(subset, 2):
            r_ff_sum += abs(df[f1].corr(df[f2]))
            num_feature_pairs += 1
        avg_r_ff = r_ff_sum / num_feature_pairs if num_feature_pairs > 0 else 0
    else:
        avg_r_ff = 0
    numerator = k * avg_r_cf
    denominator = np.sqrt(k + k * (k - 1) * avg_r_ff)
    if denominator == 0:
        return 0.0
    return numerator / denominator
features = ['x1', 'x2', 'x3']
target_col = 'y'
results = []
for i in range(1, len(features) + 1):
    for subset_tuple in combinations(features, i):
        subset = list(subset_tuple)
        merit = cfs_merit(subset, df, target_col)
        results.append({'Subset': subset, 'CFS Merit': merit})

cfs_df = pd.DataFrame(results).sort_values(by='CFS Merit', ascending=False)
display(cfs_df)

         Subset  CFS Merit
0          [x1]   0.964901
3      [x1, x2]   0.947118
1          [x2]   0.925820
6  [x1, x2, x3]   0.377869
4      [x1, x3]   0.097279
5      [x2, x3]   0.076454
2          [x3]  -0.774597